#Admin Login
POST http://localhost:5001/api/Login
Content-Type: application/json

{
  "username": "admin",
  "password": "password123"
}
################

#User login
POST http://localhost:5001/api/Login
Content-Type: application/json

{
  "username": "John",
  "password": "password"
}
################

GET http://localhost:5001/api/Events
#####

GET http://localhost:5001/api/Events/2
#####


POST http://localhost:5001/api/Events
Content-Type: application/json

{
  "Id":3,
  "Title": "Annual Conference",
  "Description": "A conference for industry professionals.",
  "EventDate": "2024-11-15",
  "StartTime": "09:00:00",
  "EndTime": "17:00:00",
  "Location": "Convention Center, Hall A",
  "AdminApproval": false
}

####

DELETE http://localhost:5001/api/Events/2
####


PUT http://localhost:5001/api/Events
Content-Type: application/json 

{
  "Id":3,
  "Title": "changed",
  "Description": "this has been changed",
  "EventDate": "2024-11-15",
  "StartTime": "09:00:00",
  "EndTime": "18:00:00",
  "Location": "Convention Center, Hall B",
  "AdminApproval": false
}

####

GET http://localhost:5001/api/Events/review


####

POST http://localhost:5001/api/Events/review
Content-Type: application/json

{
  "Id": 5,
  "User_Id": 3,
  "Event_Id":1,
  "Rating": 37,
  "Feedback": "good event really"
}

#####