
GET http://localhost:5001/hi
#######

POST http://localhost:5001/api/Login
Content-Type: application/json

{
  "username": "admin",
  "password": "idontknow"
}
################
POST http://localhost:5001/api/Login
Content-Type: application/json

{
  "username": "admin",
  "password": "password123"
}
################

POST http://localhost:5001/api/Login
Content-Type: application/json

{
  "username": "John",
  "password": "password"
}
################



GET http://localhost:5001/api/IsAdminLoggedIn
###################

GET http://localhost:5001/api/IsUserLoggedIn
###################

GET http://localhost:5001/api/Logout
###################

GET http://localhost:5001/api/AdminLogout
###################