
GET http://localhost:5001/hi
#######


POST http://localhost:5001/api/Login
Content-Type: application/json

{
  "username": "admin",
  "password": "password123"
}
################

GET http://localhost:5001/api/IsAdminLoggedIn
