#test if there is an connection
GET http://localhost:5001/hi
#######

#Invallid input
POST http://localhost:5001/api/Login
Content-Type: application/json

{
  "username": null,
  "password": null
}
################

#Wrong input
POST http://localhost:5001/api/Login
Content-Type: application/json

{
  "username": "admin",
  "password": "idontknow"
}
################

#Admin Login
POST http://localhost:5001/api/Login
Content-Type: application/json

{
  "username": "admin",
  "password": "password123"
}
################

#User login
POST http://localhost:5001/api/Login
Content-Type: application/json

{
  "username": "John",
  "password": "password"
}
################


#check if the Admin is logged in
GET http://localhost:5001/api/IsAdminLoggedIn
###################


#check if the User is logged in
GET http://localhost:5001/api/IsUserLoggedIn
###################

#logout User
GET http://localhost:5001/api/Logout
###################


#logout Admin
GET http://localhost:5001/api/AdminLogout
###################